---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/webgsm/public_html/test/wp-content
    
    - /bin/mkdir -p $DEPLOYPATH/themes
    - /bin/mkdir -p $DEPLOYPATH/plugins
    
    - /bin/cp -Rf wp-content/themes/martfury-child $DEPLOYPATH/themes/
    - /bin/cp -Rf wp-content/plugins/webgsm-b2b-pricing $DEPLOYPATH/plugins/
    - /bin/cp -Rf wp-content/plugins/webgsm-checkout-pro $DEPLOYPATH/plugins/
    - /bin/cp -Rf wp-content/plugins/webgsm-setup-wizard-v2 $DEPLOYPATH/plugins/
    
    - /bin/chmod -R 755 $DEPLOYPATH/themes/martfury-child
    - /bin/chmod -R 755 $DEPLOYPATH/plugins/webgsm-b2b-pricing
    - /bin/chmod -R 755 $DEPLOYPATH/plugins/webgsm-checkout-pro
    - /bin/chmod -R 755 $DEPLOYPATH/plugins/webgsm-setup-wizard-v2